apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-admin
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list" ]
