kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-service-account-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kebabcase-release-name" . }}-enterprise-server-service-account
roleRef:
  kind: Role
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-role
  apiGroup: rbac.authorization.k8s.io
