apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: server
{{ include "recommended-labels" . | indent 4 }}
data:
  BSEE_HTTPS_KEYSTORE_PASSWORD: {{ randAlphaNum 20 | b64enc }}