{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burpsuite
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - backend:
        path: /
        pathType: Prefix
          service:
            name: burpsuite-web-server
            port:
              name: http
{{-  end }}
