kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-web-server-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]