apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kebabcase-release-name" . }}-web-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: server
{{ include "recommended-labels" . | indent 4 }}
data:
  {{- $password := randAlphaNum 20 | b64enc }}
  BSEE_CLIENT_KEYSTORE_PASSWORD: {{ $password }}
  BSEE_CLIENT_TRUSTSTORE_PASSWORD: {{ $password }}