kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-web-server-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}